@startuml Deployment

left to right direction
skinparam componentStyle uml1

node "<<Mobile Device>>" as mobile
node "<<App Server>>" as app_server {
    node "<<ArangoDB App Service>>" as app_service
}
node "<<DB Server>>" as db_server {
    node "<<ArangoDB Database>>" as arangodb_db
}

mobile -- app_server
app_server -- app_service
app_server -- db_server
db_server -- arangodb_db

@enduml
